# Generated by Django 2.1 on 2018-08-24 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=100)),
                ('sn', models.CharField(max_length=100)),
                ('dev_id', models.CharField(max_length=100)),
                ('manuf_date', models.DateTimeField(auto_now_add=True)),
                ('descr', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Device_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField()),
                ('repaired_at', models.DateTimeField(auto_now_add=True)),
                ('fault', models.TextField()),
                ('description', models.TextField()),
                ('comments', models.TextField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.Device')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='dev_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.Device_type'),
        ),
    ]
