# Generated by Django 2.1 on 2018-08-24 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='typ',
        ),
    ]
