# Generated by Django 2.1 on 2018-08-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_device_type_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='hw_ver',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='sw_ver',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
